### PR TITLE
Fix compilation with import trees

### LINKED ISSUE #175: Large sol file with a contract and libraries - chrome browser error / unresponsive
The solidity-browser produces the following error when compiling large sol files -

   Uncaught JavaScript exception:
   RangeError: Maximum call stack size exceeded

This can be caused be the following -
  
    1. Reaching a max number of functions.
    2. Reaching a max number of events.

The same sol file compiles fine with the Microsoft Edge browser so it looks like a chrome issue.

I need to use Chrome as it supports the Metamask plugin which makes deployment and testing very easy.

### LINKED ISSUE #240: Imports chain can't be compiled
I've got the error **Uncaught JavaScript exception: RangeError: Maximum call stack size exceeded**
On Chrome, Version 53.0.2785.113 m. I use solidity version 0.4.1;

My contracts structure
file A: contract A {} - it is compiled
file B: import "A" contract B {} - it is compiled
file C: import "B" contract C {} - it can't be compiled

app.js:105644 Uncaught RangeError: Maximum call stack size exceeded
isValidError @ app.js:105644
compilationFinished @ app.js:105649
compileJSON @ app.js:105623
(anonymous function) @ app.js:105588
gatherImports @ app.js:105805
compile @ app.js:105583
compilationFinished @ app.js:105667
compileJSON @ app.js:105623
(anonymous function) @ app.js:105588
gatherImports @ app.js:105805

### PR DESCRIPTION
**Pull request by axic**
Fixes #240 and #276. (Maybe others?)

### CODE REVIEW

File: src/app/compiler.js [hunk 1]
```diff
@@ -207,9 +212,11 @@ function Compiler (editor, handleGithubCall) {
   function gatherImports (files, importHints, cb) {
     importHints = importHints || []
     if (!compilerAcceptsMultipleFiles) {
-      cb(files[editor.getCacheFile()])
+      cb(null, files[editor.getCacheFile()])
       return
     }
+    // FIXME: This will only match imports if the file begins with one.
```
Comment (chriseth) [inline src/app/compiler.js]: Note that this is only relevant for compiler versions that do not report missing inputs.
