### PR TITLE
Fix send tx through web3

### LINKED ISSUE #342: Invalid address error when using injected provider
Over at MetaMask, we had [an issue submitted](https://github.com/MetaMask/metamask-plugin/issues/880) by @drcode regarding MetaMask/browser-solidity compatibility, and I could use your help to track down.

The error thrown is `Uncaught Error: invalid address(…)`, thrown from browser-solidity when the payload has an `undefined` `from` field.

For some reason it seems that browser-solidity is no longer successfully building its transaction parameters using the currently injected selected address at `web3.eth.accounts[0]` or `web3.eth.coinbase`.

In the `Method.prototype.buildCall` function, you can see this line:
```
var payload = method.toPayload(Array.prototype.slice.call(arguments));
```

The input arguments are very minimal, and the resulting `payload` value lacks a defined sender:
```javascript
{from: undefined, to: undefined, data: "0x606060405234610000575b33600060006101000a8154817000816000905550600101610594565b5090565b50505b5056", value: "0x0", gas: 449552}
```

This makes it look like the `method.toPayload()` method is failing to pull out the current address from the injected `web3`.

Unfortunately, when I did [a search of this repository](https://github.com/ethereum/browser-solidity/search?utf8=%E2%9C%93&q=toPayload), I saw no `toPayload` reference anywhere, so now I'm confused.

This *seems to be* a browser-solidity bug to me right now, but without the original source code to search & reference, it will be hard for me to track down.  Any clues?

### PR DESCRIPTION
**Pull request by yann300**
Fixes #342.

### CODE REVIEW

**Comment by axic** [comment]
This goes against the previous design, where we have "prototype.getAccounts" doing this abstraction. Mixing external RPC addresses into the private key light might not be the best idea.

**Comment by yann300** [comment]
I thought that it is better to use the property `accounts` even in web3 mode than to leave it blank
while in web3 mode (which could loo inconsistent)
the VM and web3 make use of accounts differently (the vm need private key, web3 not), but both are still representing an account.
But I see your concern. I pushed changes

File: src/universal-dapp.js [hunk 1]
```diff
@@ -549,11 +549,14 @@ UniversalDApp.prototype.getCallButton = function (args) {
 
     var decoded
     self.runTx({ to: args.address, data: data, useCall: args.abi.constant && !isConstructor }, function (err, txResult) {
-      var result = txResult.result
+      var result
       if (err) {
         replaceOutput($result, $('<span/>').text(err).addClass('error'))
       // VM only
-      } else if (self.executionContext.isVM() && result.vm.exception === 0 && result.vm.exceptionError) {
```
Comment (axic) [inline src/universal-dapp.js]: This seems to be wrong, all the conditions below are error cases.

Maybe it would be better adding an extra condition before all these:
```
if (!err) {
  result = txResult.result
}
```

**Comment by axic** [comment]
@yann300 updated with a change to txResult

**Comment by kumavis** [comment]
tests are failing @yann300

**Comment by yann300** [comment]
yes that's fine now

**Comment by kumavis** [comment]
@axic ready for you

File: src/universal-dapp.js [hunk 2]
```diff
@@ -58,6 +54,10 @@ UniversalDApp.prototype.reset = function (contracts, getAddress, getValue, getGa
     this._addAccount('d74aa6d18aa79a05f3473dd030a97d3305737cbc8337d940344345c1f6b72eea')
     this._addAccount('71975fbf7fe448e004ac7ae54cad0a383c3906055a65468714156a07385e96ce')
   }
+  this.txRunner = new TxRunner(this.executionContext, this.accounts, {
```
Comment (axic) [inline src/universal-dapp.js]: Since we have the `opts` field, shouldn't `accounts` (and maybe even `executionContext`) be part of it? I'm just wondering.

**Comment by axic** [comment]
@yann300 it seems you've force pushed over my commit?

**Comment by axic** [comment]
Added back my change to the 'fix txResult' commit.

**Comment by yann300** [comment]
oh ok sorry for that

File: src/universal-dapp.js (hunk 2 above)
Comment (yann300) [inline src/universal-dapp.js]: hmm so i see in opts just a param used to modify the behavior of txrunner.
executionContext and accounts are more kind of required parameters.

Comment (axic) [inline src/universal-dapp.js]: Well, we can cleanup the `txRunner` in another PR 😉
