### PR TITLE
Fix file exist (from fileProvider)

### LINKED ISSUE #1065: Fix createNonClashingName
it should be `async`
it also means that we should make `fileprovider.exists` async for every provider.

### PR DESCRIPTION
**Pull request by yann300**
fixes #1065

### CODE REVIEW

File: src/app.js [hunk 1]
```diff
@@ -3,6 +3,7 @@
 var $ = require('jquery')
 var csjs = require('csjs-inject')
 var yo = require('yo-yo')
+var async = require('async')
```
Comment (axic) [inline src/app.js]: Probably not a good idea `async` is a keyword in ES6?

Comment (iurimatias) [reply src/app.js]: That's a very interesting point. I found this discussion from a year ago in their github repo [caolan/async#1179](https://github.com/caolan/async/issues/1179)

It's not necessarily a big issue right unless we start using ES7 and the functionality itself. We were already using this lib in other sections of the code and this is not specific to this PR. So I suggest that if we do want to address did then we can do a different PR that changes all references to ```async``` to ```asyncJS```
